// Code generated by coroc. DO NOT EDIT

package main

import _types "github.com/stealthrocket/coroutine/types"

func init() {
	_types.RegisterFunc[func()]("github.com/stealthrocket/coroutine/compiler/testdata/http.init")
	_types.RegisterFunc[func()]("github.com/stealthrocket/coroutine/compiler/testdata/http.main")
	_types.RegisterFunc[func()]("github.com/stealthrocket/coroutine/compiler/testdata/http.work")
}
