//go:build !durable && !durable && !durable

// Code generated by coroc. DO NOT EDIT

// Code generated by coroc. DO NOT EDIT

// Code generated by coroc. DO NOT EDIT

// Code generated by coroc. DO NOT EDIT

// Code generated by coroc. DO NOT EDIT

// Code generated by coroc. DO NOT EDIT

package testdata

const (
	Fizz     = -1
	Buzz     = -2
	FizzBuzz = -3
)
