// Code generated by coroc. DO NOT EDIT

//go:build durable

package testdata

import "github.com/stealthrocket/coroutine"

func Identity(n int) { _c := coroutine.LoadContext[int, any](); _f := _c.Push() }

func SquareGenerator(n int) { _c := coroutine.LoadContext[int, any](); _f := _c.Push() }
